# Generated by Django 2.2.6 on 2019-10-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='english',
            old_name='image',
            new_name='text',
        ),
    ]
